'use client';

import React, { useState } from 'react';
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  Paper,
  Box,
  Typography,
  CircularProgress,
  IconButton,
  Tooltip,
  Button,
  useTheme,
  alpha,
} from '@mui/material';
import { Edit, Delete, PictureAsPdf } from '@mui/icons-material';

/* ── Client-side PDF export via print ────────────────────── */
function exportTableToPdf(columns, data, title = 'Data Export') {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const headers = columns.filter((c) => c.id !== 'pdf' && c.id !== 'invoice');
  const rows = data.map((row) =>
    headers.map((col) => {
      const val = row?.[col.id];
      if (col.exportFormat) return col.exportFormat(val, row);
      if (typeof val === 'object' && val !== null) {
        if (val.fullName) return val.fullName;
        if (val.manufacturer) return `${val.manufacturer} ${val.model || ''}`;
        return JSON.stringify(val);
      }
      return val ?? '-';
    })
  );

  const html = `<!DOCTYPE html>
<html><head><title>${title}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; padding: 30px; color: #1e293b; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
  .subtitle { font-size: 12px; color: #64748b; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #f1f5f9; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; 
       font-size: 10px; color: #475569; padding: 10px 12px; text-align: left; border-bottom: 2px solid #e2e8f0; }
  td { padding: 9px 12px; border-bottom: 1px solid #f1f5f9; }
  tr:nth-child(even) { background: #fafbfc; }
  .footer { margin-top: 30px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
  @media print { body { padding: 15px; } }
</style>
</head><body>
<h1>${title}</h1>
<div class="subtitle">Exported on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()} • Easyvate Car Management</div>
<table>
<thead><tr>${headers.map((h) => `<th>${h.label}</th>`).join('')}</tr></thead>
<tbody>${rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody>
</table>
<div class="footer">Generated by Easyvate Car Selling Management System</div>
</body></html>`;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => { printWindow.print(); printWindow.close(); }, 400);
}

/* ── Table component ─────────────────────────────────────── */
const EnhancedDataTable = ({
  columns,
  data,
  onEdit,
  onDelete,
  loading = false,
  emptyMessage = 'No data available',
  rowsPerPageOptions = [5, 10, 25, 50],
  defaultRowsPerPage = 10,
  toolbar,
  title,
  exportable = true,
}) => {
  const theme = useTheme();
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(defaultRowsPerPage);

  const handleChangePage = (_, newPage) => setPage(newPage);
  const handleChangeRowsPerPage = (e) => {
    setRowsPerPage(parseInt(e.target.value, 10));
    setPage(0);
  };

  const paginatedData = data.slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage);

  return (
    <Box sx={{ width: '100%' }}>
      {/* Toolbar area */}
      {(toolbar || (exportable && data.length > 0)) && (
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1.5 }}>
          <Box>{toolbar}</Box>
          {exportable && data.length > 0 && (
            <Tooltip title="Export to PDF">
              <Button
                size="small"
                variant="outlined"
                startIcon={<PictureAsPdf />}
                onClick={() => exportTableToPdf(columns, data, title || 'Data Export')}
                sx={{
                  borderColor: theme.palette.divider,
                  color: theme.palette.text.secondary,
                  fontWeight: 600,
                  fontSize: '0.78rem',
                  '&:hover': {
                    borderColor: theme.palette.primary.main,
                    color: theme.palette.primary.main,
                    bgcolor: alpha(theme.palette.primary.main, 0.04),
                  },
                }}
              >
                Export PDF
              </Button>
            </Tooltip>
          )}
        </Box>
      )}

      <TableContainer
        component={Paper}
        sx={{
          position: 'relative',
          borderRadius: `${theme.shape.borderRadius}px`,
          border: `1px solid ${theme.palette.divider}`,
          overflowX: 'auto',
          overflowY: 'auto',
          maxHeight: 'calc(100vh - 300px)',
          minHeight: 200,
          '&::-webkit-scrollbar': { width: 8, height: 8 },
          '&::-webkit-scrollbar-thumb': {
            backgroundColor: alpha(theme.palette.text.primary, 0.25),
            borderRadius: 4,
          },
          '&::-webkit-scrollbar-thumb:hover': {
            backgroundColor: alpha(theme.palette.text.primary, 0.4),
          },
          '&::-webkit-scrollbar-track': {
            backgroundColor: alpha(theme.palette.text.primary, 0.05),
            borderRadius: 4,
          },
        }}
      >
        {loading && (
          <Box
            sx={{
              position: 'absolute',
              inset: 0,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              zIndex: 20,
              bgcolor: alpha(theme.palette.background.paper, 0.8),
              backdropFilter: 'blur(2px)',
            }}
          >
            <CircularProgress size={28} />
            <Typography variant="body2" sx={{ ml: 1.5, fontWeight: 500 }}>
              Loading...
            </Typography>
          </Box>
        )}

        <Table stickyHeader sx={{ minWidth: 650 }}>
          <TableHead>
            <TableRow>
              {columns.map((column) => (
                <TableCell
                  key={column.id}
                  align={column.align || 'left'}
                  sx={{
                    width: column.width || 'auto',
                    display: column.hiddenOnMobile
                      ? { xs: 'none', sm: 'table-cell' }
                      : 'table-cell',
                    whiteSpace: 'nowrap',
                    bgcolor: theme.palette.background.paper,
                  }}
                >
                  {column.label}
                </TableCell>
              ))}
              {(onEdit || onDelete) && (
                <TableCell align="center" sx={{ width: '110px', whiteSpace: 'nowrap', bgcolor: theme.palette.background.paper }}>
                  Actions
                </TableCell>
              )}
            </TableRow>
          </TableHead>

          <TableBody>
            {paginatedData.length > 0 ? (
              paginatedData.map((row, rowIndex) => (
                <TableRow key={row.id || rowIndex}>
                  {columns.map((column) => {
                    const value = row?.[column.id];
                    return (
                      <TableCell
                        key={`${row.id || rowIndex}-${column.id}`}
                        align={column.align || 'left'}
                        sx={{
                          display: column.hiddenOnMobile
                            ? { xs: 'none', sm: 'table-cell' }
                            : 'table-cell',
                          fontWeight: column.bold ? 600 : 400,
                          color: typeof column.color === 'function'
                            ? column.color(value, row)
                            : column.color || 'inherit',
                        }}
                      >
                        {column.format ? column.format(value, row) : value ?? '-'}
                      </TableCell>
                    );
                  })}
                  {(onEdit || onDelete) && (
                    <TableCell align="center" sx={{ width: '110px' }}>
                      <Box sx={{ display: 'flex', gap: 0.5, justifyContent: 'center' }}>
                        {onEdit && (
                          <Tooltip title="Edit">
                            <IconButton
                              size="small"
                              onClick={() => onEdit(row)}
                              sx={{
                                color: theme.palette.primary.main,
                                '&:hover': {
                                  bgcolor: alpha(theme.palette.primary.main, 0.08),
                                },
                              }}
                            >
                              <Edit fontSize="small" />
                            </IconButton>
                          </Tooltip>
                        )}
                        {onDelete && (
                          <Tooltip title="Delete">
                            <IconButton
                              size="small"
                              onClick={() => onDelete(row.id)}
                              sx={{
                                color: theme.palette.error.main,
                                '&:hover': {
                                  bgcolor: alpha(theme.palette.error.main, 0.08),
                                },
                              }}
                            >
                              <Delete fontSize="small" />
                            </IconButton>
                          </Tooltip>
                        )}
                      </Box>
                    </TableCell>
                  )}
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell
                  colSpan={columns.length + (onEdit || onDelete ? 1 : 0)}
                  align="center"
                  sx={{ py: 5 }}
                >
                  <Typography color="text.secondary" sx={{ fontSize: '0.9rem' }}>
                    {emptyMessage}
                  </Typography>
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </TableContainer>

      {data.length > 0 && (
        <TablePagination
          rowsPerPageOptions={rowsPerPageOptions}
          component="div"
          count={data.length}
          rowsPerPage={rowsPerPage}
          page={page}
          onPageChange={handleChangePage}
          onRowsPerPageChange={handleChangeRowsPerPage}
          sx={{ borderTop: `1px solid ${theme.palette.divider}` }}
        />
      )}
    </Box>
  );
};

export default EnhancedDataTable;
